### PR TITLE
Google auth front end

### LINKED ISSUE #9: Google OAuth
Add functionality to the login button → OAuth. Check out [https://developers.google.com/identity/sign-in/web/sign-in[](https://reactjs.org/docs/context.html)](https://developers.google.com/identity/sign-in/web/sign-in) to get started. 

----------------

You will also most likely need to make use of React Context

- Here’s some good documention on it: [https://reactjs.org/docs/context.html[](https://blog.prototypr.io/how-to-build-google-login-into-a-react-app-and-node-express-api-821d049ee670)](https://reactjs.org/docs/context.html)
    - Please read it fully first, but if you have questions along the way feel free to ask us, but maybe ask Ranon

----------------

It may also be worthwhile to search up on guides/tips on this process. You’re definitely going to have to adapt these resources at least a bit, and not everything on the resources may be relevant, but they may help to point you guys in the right direction

- Here’s an example of one; I very much just scanned through this so idk if it’s actually good or useful but it seems like a decent starting point: [https://blog.prototypr.io/how-to-build-google-login-into-a-react-app-and-node-express-api-821d049ee670](https://blog.prototypr.io/how-to-build-google-login-into-a-react-app-and-node-express-api-821d049ee670)

### PR DESCRIPTION
**Pull request by mawilh0721**
## Motivation

The functionality of google oAuth to distinguish between user and admin access is implemented and fully functional. 

Fixes #9 

## Summary of Changes

The functionality of google oAuth is there. However, there needs to be changes with css styling of the login into google button. Alongside, there is a navbar button bug that still exists, where if you click on login, you can't click on the other components of the navBar. But that is on the navBar PR task team to fix :) 
Screen Shot 2022-04-29 at 12 16 43 AM

### CODE REVIEW

**Comment by ilyues** [comment]
Screen Shot 2022-04-29 at 12 26 39 AM
you're great mawil. fix this tho

**Comment by ilyues** [comment]
/ the div is covering the links in the navbar which is why theyre unclickable -- the div was correctly height-adjusted (94vh) but not positioned correctly now in relation to the navbar

**Comment by ilyues** [comment]
nice! before u merge: will this merge prevent everyone else from accessing the admin pages easily if we can't log in LOL

**Review by ranonl — APPROVED** [review]
Thanks for the super super super hard work on this Mawil. Just got the same question as Isabel on this as well cuz if not it'll be slightly annoying to debug/test/demo. Also, I'll let you know what Dharma says about who's using the app

**Review by ilyues — APPROVED** [review]
woohoo! let's get this merged, super super super great job on this !

**Pull request merged**
